# Generated by Django 3.2.5 on 2021-07-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualapp', '0002_assignment_assignmentno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submissionID', models.AutoField(primary_key=True, serialize=False)),
                ('assignmentId', models.IntegerField(default=0)),
                ('studentId', models.IntegerField(default=0)),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'submission',
            },
        ),
    ]
