# Generated by Django 3.2.5 on 2021-07-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualapp', '0003_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredStudents',
            fields=[
                ('RegID', models.AutoField(primary_key=True, serialize=False)),
                ('courseId', models.IntegerField(default=0)),
                ('studentId', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'RegisteredStudents',
            },
        ),
    ]
